name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        php:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
        LARAVEL:
          - 5.5.*
          - 5.6.*
          - 5.7.*
          - 5.8.*
          - 6.0.*
          - 6.1.*
          - 6.2.*
          - 6.3.*
          - 6.4.*
          - 6.5.*
          - 6.6.*
        exclude:
          - php: 7.1
            LARAVEL: 6.0.*
          - php: 7.1
            LARAVEL: 6.1.*
          - php: 7.1
            LARAVEL: 6.2.*
          - php: 7.1
            LARAVEL: 6.3.*
          - php: 7.1
            LARAVEL: 6.4.*
          - php: 7.1
            LARAVEL: 6.5.*
          - php: 7.1
            LARAVEL: 6.6.*

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setting up PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extension-csv: curl, dom, json, mbstring, openssl
          coverage: xdebug
          pecl: false

      - name: Check PHP
        run: |
          php -v
          php -m
          composer -v

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: |
          composer require --no-interaction --no-update "illuminate/support:${{ matrix.LARAVEL }}"
          composer update --no-interaction --no-suggest --prefer-dist $COMPOSER_ARGS

      - name: Check coding style
        run: php vendor/bin/phpcs --standard=phpcs.xml.dist

      - name: Run PHPUnit
        run: php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

      # - name: Update test coverage
      #   if: matrix.php == '7.4' && matrix.LARAVEL == '6.6.*'
      #   run: |
      #     composer require php-coveralls/php-coveralls
      #     php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
